services:
  - type: web
    name: botc-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python botc-bot.py
    disk:
      name: botc-data
      mountPath: /opt/render/project/src
      sizeGB: 1